import React from 'react';
import { Table, Divider, Tag } from 'antd';
import "./AntForumBoard.css"


import PropTypes from 'prop-types';
import { Route, Link, BrowserRouter as Router } from 'react-router-dom';
import Thread from './Thread.js'
import { fetchThreadTopics } from "./redux/actions/threadTopicActions.js";
import { connect } from "react-redux";

import AntThread from './AntThread.js';

import AntForumPost from './AntForumPost.js'

/** 
The table is generated by specifying a fields object and a data object, then passing them to the Table Object.
**/
/** 
Fields we want: Title Summary Creator

TODO: Find a way to fit the data from the DB into the fields we have for the table. Create the data obj, so it can be dynamic.
**/

class ForumComments extends React.Component {
  componentDidMount(){
    console.log("component did mount of forum comments")
    // here is where we should query the data for our posts
  }
  render (){
    /** 
    generate data for the table from the queries
    **/

    let myProps1 = {
      "username": "NarutoLover44",
      "profilePic": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
      "indentationLevel": 1,
      "comment": "This is all the text for the description. I can place any text I want here and it will show up below.",
      "ts": "some datetime obj here"
    }

    let myProps2 = {
      "username": "sasukeIsTheBest",
      "profilePic": "https://i.pinimg.com/236x/77/7b/63/777b632c2c3601eca106352ddbccb07d.jpg",
      "indentationLevel": 2,
      "comment": "This is a comment that is suppose to be a reply to the one above! Let's see if it works. it should be indented since it's a reply.",
      "ts": "some datetime obj here"
    }

    let myProps3 = {
      "username": "GenfiWatchMoreHunterxHunter",
      "profilePic": "https://www.gstatic.com/tv/thumb/tvbanners/10964192/p10964192_b_v8_aa.jpg",
      "indentationLevel": 3,
      "comment": "This comment has an indentation level of 3, so it should be a comment of the nested comment! this doesn't look too bad so far if i say so myself.",
      "ts": "some datetime obj here"
    }

    let myProps4 = {
      "username": "TheReasonableGuy72",
      "profilePic": "https://qph.fs.quoracdn.net/main-qimg-affdc3d2c25fe8afb9d5d9cff88d9a29",
      "indentationLevel": 2,
      "comment": "Though, I'm not sure how much sense it makes to have three levels of indents... Many places only offer a couple, like facebook.",
      "ts": "some datetime obj here"
    }

    let allPosts = []
    allPosts.push(<AntForumPost data={myProps1}/>)
    allPosts.push(<AntForumPost data={myProps2}/>)
    allPosts.push(<AntForumPost data={myProps3}/>)
    allPosts.push(<AntForumPost data={myProps4}/>)
    return (
      <>
      {allPosts}
      </>
    );
  }
}

export default ForumComments;


