import React from 'react';
import { Table, Divider, Tag } from 'antd';
import "./ForumComments.css"


import PropTypes from 'prop-types';
import { Route, Link, BrowserRouter as Router } from 'react-router-dom';
import Thread from './Thread.js'
import { fetchThreadTopics } from "./redux/actions/threadTopicActions.js";
import { connect } from "react-redux";

import AntThread from './AntThread.js';

import AntForumPost from './AntForumPost.js'
import ForumComments from './ForumComments.js'

/** 
The table is generated by specifying a fields object and a data object, then passing them to the Table Object.
**/
/** 
Fields we want: Title Summary Creator

TODO: Find a way to fit the data from the DB into the fields we have for the table. Create the data obj, so it can be dynamic.
**/

class ForumBoard extends React.Component {
  componentDidMount(){
    console.log("component did mount of forum comments")
    // here is where we should query the data for our posts
  }
  render (){
    /** 
    generate data for the table from the queries
    **/

    
    // this should be taken in by props
    let titleProps = {
      "username": "CrazyClownMan",
      "profilePic": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d7c99ebb-62eb-45ff-8ecf-da92d86c6d59/ddp780g-10c2a033-2863-467e-b9e8-16d0fd22c790.png/v1/fill/w_1024,h_1450,q_80,strp/hxh___hisoka_morrow_by_khalilxpirates_ddp780g-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD0xNDUwIiwicGF0aCI6IlwvZlwvZDdjOTllYmItNjJlYi00NWZmLThlY2YtZGE5MmQ4NmM2ZDU5XC9kZHA3ODBnLTEwYzJhMDMzLTI4NjMtNDY3ZS1iOWU4LTE2ZDBmZDIyYzc5MC5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19._qDuMYQrCxygXSCjKXML2mY2f6u-9Ubq0foxa0Xs1bI",
      "comment": "This is the main post test! Let's see how this goes.",
      "isMainPost": true,
      "title": "This is my main post title",
      "ts": "some datetime obj here"
    }

    // we should fill forumcomments with props that we get from querying data related to the topic that's placed

    return (
      <>
      <AntForumPost data={titleProps}/>
      <ForumComments />
      </>
    );
  }
}

export default ForumBoard;


